- id: doi:10.1093/nar/gkae1029
  image: images/ecod2024.jpeg
  buttons:
    - type: website
      link: http://prodata.swmed.edu/ecod/

- id: doi:10.1002/pro.5116
  image: images/drugdomain_logo_fin.png
  buttons:
    - type: website
      link: http://prodata.swmed.edu/DrugDomain/
      
